apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "28"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"user-service","namespace":"user-service"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"user-service"}},"template":{"metadata":{"labels":{"app":"user-service"}},"spec":{"containers":[{"env":[{"name":"SPRING_CONFIG_LOCATION","value":"/config/application.yml"},{"name":"ENCRYPTION_KEY","valueFrom":{"secretKeyRef":{"key":"encryption.key","name":"encryption-secret"}}},{"name":"AZURE_EVENTHUBS_CONNECTION_STRING","value":"Endpoint=sb://sangsangplus-eventhubs.servicebus.windows.net/;SharedAccessKeyName=UserProducerKey;SharedAccessKey=X4eEsDXqTiDAu9BBQBKNnfDQ7k77ffboz+AEhO7s8iA="}],"image":"buildingbite/sangsangplus-user:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/api/users/health","port":8081},"initialDelaySeconds":60,"periodSeconds":30},"name":"user-service","ports":[{"containerPort":8081}],"readinessProbe":{"httpGet":{"path":"/api/users/health","port":8081},"initialDelaySeconds":30,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/config","name":"config-volume"}]}],"volumes":[{"configMap":{"name":"user-service-config"},"name":"config-volume"}]}}}}
  creationTimestamp: "2025-07-17T12:55:14Z"
  generation: 31
  name: user-service
  namespace: user-service
  resourceVersion: "1087272"
  uid: 44631e52-c21a-46af-813d-9a9595d6316b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-28T02:46:03Z"
      creationTimestamp: null
      labels:
        app: user-service
    spec:
      containers:
      - env:
        - name: SPRING_CONFIG_LOCATION
          value: /config/application.yml
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: encryption.key
              name: encryption-secret
        - name: AZURE_EVENTHUBS_CONNECTION_STRING
          value: Endpoint=sb://sangsangplus-eventhubs.servicebus.windows.net/;SharedAccessKeyName=UserProducerKey;SharedAccessKey=X4eEsDXqTiDAu9BBQBKNnfDQ7k77ffboz+AEhO7s8iA=
        image: buildingbite/sangsangplus-user:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/users/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: user-service
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/users/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: user-service-config
        name: config-volume
status:
  conditions:
  - lastTransitionTime: "2025-07-28T02:21:48Z"
    lastUpdateTime: "2025-07-28T02:21:48Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-07-28T02:43:18Z"
    lastUpdateTime: "2025-07-28T02:46:03Z"
    message: ReplicaSet "user-service-589cbd7f69" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 31
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
