version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sangsang-plus

  # Axon Server
  axonserver:
    image: axoniq/axonserver
    container_name: user-service-axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - axonserver_data:/data
      - axonserver_events:/eventdata
      - axonserver_config:/config
    networks:
      - sangsang-plus

  # User Service Application
  user-service:
    build: .
    container_name: user-service-app
    depends_on:
      - postgres
      - axonserver
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_AXON_AXONSERVER_SERVERS: axonserver:8124
    networks:
      - sangsang-plus
    restart: unless-stopped

networks:
  sangsang-plus:
    external: true

volumes:
  postgres_data:
  axonserver_data:
  axonserver_events:
  axonserver_config: