server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: user-service
  
  # encryption Config: Reads key from environment variable
  encryption:
    key: ${ENCRYPTION_KEY}
    
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/userdb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # kafka Configuration (local development)
  kafka:
    bootstrap-servers: kafka:9092
  
  # Azure Event Hubs Configuration (override in k8s)
  azure:
    eventhubs:
      connection-string: ""
