apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: user-service
data:
  application.yml: |
    server:
      port: 8081
      forward-headers-strategy: framework

    spring:
      application:
        name: user-service
      
      # encryption Config: 64 Hex Key(32bytes) for AES-256
      encryption:
        key: ${ENCRYPTION_KEY:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
        
      # kafka Configuration
      kafka:
        bootstrap-servers: kafka-service:9092
        
      datasource:
        url: jdbc:postgresql://postgres-service:5432/userdb
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: ${DATABASE_PASSWORD:postgres}
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        show-sql: false
      security:
        oauth2:
          client:
            registration:
              google:
                client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
                client-secret: ${GOOGLE_CLIENT_SECRET}
                scope:
                  - email
                  - profile
                redirect-uri: "https://oauth.buildingbite.com/login/oauth2/code/google"
            provider:
              google:
                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                token-uri: https://oauth2.googleapis.com/token
                user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
                user-name-attribute: email