apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: user-service
data:
  application.yml: |
    server:
      port: 8081
      forward-headers-strategy: framework

    spring:
      application:
        name: user-service
      
      # encryption Config: 64 Hex Key(32bytes) for AES-256
      encryption:
        key: ${ENCRYPTION_KEY:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
        
      # kafka Configuration
      kafka:
        bootstrap-servers: sangsangplus-eventhubs.servicebus.windows.net:9093
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          acks: all
          retries: 2147483647
          properties:
            security.protocol: SASL_SSL
            sasl.mechanism: PLAIN
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://sangsangplus-eventhubs.servicebus.windows.net/;SharedAccessKeyName=UserProducerKey;SharedAccessKey=X4eEsDXqTiDAu9BBQBKNnfDQ7k77ffboz+AEhO7s8iA=";
            client.dns.lookup: use_all_dns_ips
            session.timeout.ms: 30000
            max.in.flight.requests.per.connection: 5
            enable.idempotence: true
        
      datasource:
        url: jdbc:postgresql://postgres-service:5432/userdb
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: ${DATABASE_PASSWORD:postgres}
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        show-sql: false