apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: sangsangplus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: buildingbite/sangsangplus-user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_CONFIG_LOCATION
          value: /config/application.yml
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: azure-postgres-secret
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: azure-postgres-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-postgres-secret
              key: DATABASE_PASSWORD
        - name: AZURE_EVENTHUBS_CONNECTION_STRING
          value: "Endpoint=sb://sangsangplus-eventhubs.servicebus.windows.net/;SharedAccessKeyName=UserProducerKey;SharedAccessKey=bL7m6coLCPDiFgnhFOg6HzQ+FSPhkjsBG+AEhPFs8ys=;EntityPath=user-events"
        - name: AZURE_EVENTHUBS_NAMESPACE
          value: "sangsangplus-eventhubs"
        - name: AZURE_EVENTHUB_NAME
          value: "user-events"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        resources:
          requests:
            memory: "400Mi"
            cpu: "65m"
          limits:
            memory: "768Mi"
            cpu: "650m"
        livenessProbe:
          httpGet:
            path: /api/users/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/users/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: user-service-config
          
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sangsangplus-backend
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8081

    protocol: TCP

